import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";

import Header from "@/components/layout/Header";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({
  variable: "--font-outfit",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} font-sans`}>
      <body className={`${outfit.variable} antialiased`}>
        <Header />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
